##### Install requirements

In [3]:
import pandas as pd
import requests

##### Loading the CSV file

In [4]:
takeoffs2016 = pd.read_csv("data/2016.csv")

In [5]:
takeoffs2017 = pd.read_csv("data/2017.csv")

In [6]:
takeoffs2018 = pd.read_csv("data/2018.csv")

#### Create Launch Sites

In [7]:
print(takeoffs2016.head())

      FL_DATE OP_CARRIER  OP_CARRIER_FL_NUM ORIGIN DEST  CRS_DEP_TIME  \
0  2016-01-01         DL               1248    DTW  LAX          1935
1  2016-01-01         DL               1251    ATL  GRR          2125
2  2016-01-01         DL               1254    LAX  ATL          2255
3  2016-01-01         DL               1255    SLC  ATL          1656
4  2016-01-01         DL               1256    BZN  MSP           900

   DEP_TIME  DEP_DELAY  TAXI_OUT  WHEELS_OFF  ...  CRS_ELAPSED_TIME  \
0    1935.0        0.0      23.0      1958.0  ...             309.0
1    2130.0        5.0      13.0      2143.0  ...             116.0
2    2256.0        1.0      19.0      2315.0  ...             245.0
3    1700.0        4.0      12.0      1712.0  ...             213.0
4    1012.0       72.0      63.0      1115.0  ...             136.0

   ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  CARRIER_DELAY  WEATHER_DELAY  \
0                285.0     249.0    1979.0            NaN            NaN
1                109.0      92.0     640.0            NaN            NaN
2                231.0     207.0    1947.0            NaN            NaN
3                193.0     173.0    1590.0            NaN            NaN
4                188.0     121.0     874.0           72.0            0.0

  NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY  Unnamed: 27
0       NaN             NaN                  NaN          NaN
1       NaN             NaN                  NaN          NaN
2       NaN             NaN                  NaN          NaN
3       NaN             NaN                  NaN          NaN
4      52.0             0.0                  0.0          NaN

[5 rows x 28 columns]

In [8]:
takeoffs2016['ORIGIN'].unique()

<StringArray>
['DTW', 'ATL', 'LAX', 'SLC', 'BZN', 'BNA', 'JAX', 'MSP', 'MDT', 'SAV',
 ...
 'GCK', 'GST', 'AKN', 'DLG', 'ABI', 'GRI', 'EFD', 'SPN', 'PGD', 'ENV']
Length: 313, dtype: str

In [9]:
AIRPORTS = {
    'Atlanta ATL': (36.63,  84.43),
    'Los Angeles LAX': (28.50,  -80.57),
    'Pittsburgh PIT': (34.74, -120.57),
    'Seattle SEA': (45.92,   63.34),
    'Dallas Fort Worth DFW': (5.24,  -52.77),
    'Denver DEN': (13.73,   80.23),
}

print(f'Airports being used: {len(AIRPORTS)}')
for name, (lat, lon) in AIRPORTS.items():
    print(f'  {name}: ({lat}, {lon})')

Airports being used: 6
  Atlanta ATL: (36.63, 84.43)
  Los Angeles LAX: (28.5, -80.57)
  Pittsburgh PIT: (34.74, -120.57)
  Seattle SEA: (45.92, 63.34)
  Dallas Fort Worth DFW: (5.24, -52.77)
  Denver DEN: (13.73, 80.23)

In [29]:
import pandas as pd
import requests

url = "https://archive-api.open-meteo.com/v1/archive"
timeout = 30

AIRPORTS = {
    "ATL": (33.6407, -84.4277),
    "LAX": (33.9416, -118.4085),
    "ORD": (41.9742, -87.9073),
    "DFW": (32.8998, -97.0403),
    "DEN": (39.8561, -104.6737),
    "SEA": (47.4502, -122.3088),
}

def get_airport_weather(start_date="2016-01-01", end_date="2018-12-31"):
    all_weather = []

    for airport_code, (lat, lon) in AIRPORTS.items():
        params = {
            "latitude": lat,
            "longitude": lon,
            "start_date": start_date,
            "end_date": end_date,
            "daily": [
                "temperature_2m_max",
                "temperature_2m_min",
                "precipitation_sum",
                "snowfall_sum",
                "wind_speed_10m_max",
                "weather_code",
            ],
            "temperature_unit": "celsius",
            "wind_speed_unit": "mph",
            "precipitation_unit": "mm",
            "timezone": "auto",
        }

        response = requests.get(url, params=params, timeout=timeout)
        response.raise_for_status()

        data = response.json()
        daily = data["daily"]

        airport_df = pd.DataFrame({
            "airport_code": airport_code,
            "date": daily["time"],
            "temp_max_c": daily["temperature_2m_max"],
            "temp_min_c": daily["temperature_2m_min"],
            "precipitation_mm": daily["precipitation_sum"],
            "snow_mm": daily["snowfall_sum"],
            "wind_speed_mph": daily["wind_speed_10m_max"],
            "weather_code": daily["weather_code"],
        })

        all_weather.append(airport_df)

    return pd.concat(all_weather, ignore_index=True)

In [30]:
airport_weather = get_airport_weather()

airport_weather["date"] = pd.to_datetime(airport_weather["date"])

airport_weather.head()

,airport_code,date,temp_max_c,temp_min_c,precipitation_mm,snow_mm,wind_speed_mph,weather_code
0,ATL,2016-01-01,10.2,5.4,0.0,0.0,12.2,3
1,ATL,2016-01-02,8.8,1.8,0.0,0.0,10.7,3
2,ATL,2016-01-03,11.0,1.4,0.0,0.0,9.4,3
3,ATL,2016-01-04,6.5,0.3,0.0,0.0,15.4,0
4,ATL,2016-01-05,5.1,-4.0,0.0,0.0,9.4,0

#### Looking at the Structure of CSV

In [12]:
takeoffs2016[takeoffs2016["DEP_TIME"].isna()][["FL_DATE", "DEP_DELAY", "DEP_TIME"]]

            FL_DATE  DEP_DELAY  DEP_TIME
699      2016-01-01        NaN       NaN
710      2016-01-01        NaN       NaN
713      2016-01-01        NaN       NaN
1231     2016-01-01        NaN       NaN
1242     2016-01-01        NaN       NaN
...             ...        ...       ...
5611879  2016-12-31        NaN       NaN
5614160  2016-12-31        NaN       NaN
5614414  2016-12-31        NaN       NaN
5616755  2016-12-31        NaN       NaN
5616782  2016-12-31        NaN       NaN

[63456 rows x 3 columns]

In [13]:
print(takeoffs2016.dtypes)

FL_DATE                    str
OP_CARRIER                 str
OP_CARRIER_FL_NUM        int64
ORIGIN                     str
DEST                       str
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float64
TAXI_OUT               float64
WHEELS_OFF             float64
WHEELS_ON              float64
TAXI_IN                float64
CRS_ARR_TIME             int64
ARR_TIME               float64
ARR_DELAY              float64
CANCELLED              float64
CANCELLATION_CODE          str
DIVERTED               float64
CRS_ELAPSED_TIME       float64
ACTUAL_ELAPSED_TIME    float64
AIR_TIME               float64
DISTANCE               float64
CARRIER_DELAY          float64
WEATHER_DELAY          float64
NAS_DELAY              float64
SECURITY_DELAY         float64
LATE_AIRCRAFT_DELAY    float64
Unnamed: 27            float64
dtype: object

In [14]:
print(takeoffs2017.dtypes)

FL_DATE                    str
OP_CARRIER                 str
OP_CARRIER_FL_NUM        int64
ORIGIN                     str
DEST                       str
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float64
TAXI_OUT               float64
WHEELS_OFF             float64
WHEELS_ON              float64
TAXI_IN                float64
CRS_ARR_TIME             int64
ARR_TIME               float64
ARR_DELAY              float64
CANCELLED              float64
CANCELLATION_CODE          str
DIVERTED               float64
CRS_ELAPSED_TIME       float64
ACTUAL_ELAPSED_TIME    float64
AIR_TIME               float64
DISTANCE               float64
CARRIER_DELAY          float64
WEATHER_DELAY          float64
NAS_DELAY              float64
SECURITY_DELAY         float64
LATE_AIRCRAFT_DELAY    float64
Unnamed: 27            float64
dtype: object

In [15]:
print(takeoffs2018.dtypes)

FL_DATE                    str
OP_CARRIER                 str
OP_CARRIER_FL_NUM        int64
ORIGIN                     str
DEST                       str
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float64
TAXI_OUT               float64
WHEELS_OFF             float64
WHEELS_ON              float64
TAXI_IN                float64
CRS_ARR_TIME             int64
ARR_TIME               float64
ARR_DELAY              float64
CANCELLED              float64
CANCELLATION_CODE          str
DIVERTED               float64
CRS_ELAPSED_TIME       float64
ACTUAL_ELAPSED_TIME    float64
AIR_TIME               float64
DISTANCE               float64
CARRIER_DELAY          float64
WEATHER_DELAY          float64
NAS_DELAY              float64
SECURITY_DELAY         float64
LATE_AIRCRAFT_DELAY    float64
Unnamed: 27            float64
dtype: object

### Cleaning data

##### Takeoff changes

In [16]:
takeoffs2016['FL_DATE'] = pd.to_datetime(takeoffs2016['FL_DATE'], format = 'mixed')

In [17]:
takeoffs2017['FL_DATE'] = pd.to_datetime(takeoffs2017['FL_DATE'], format = 'mixed')

In [18]:
takeoffs2018['FL_DATE'] = pd.to_datetime(takeoffs2018['FL_DATE'], format = 'mixed')

In [19]:
print(takeoffs2016['FL_DATE'].head())
print(takeoffs2017['FL_DATE'].head())
print(takeoffs2018['FL_DATE'].head())

0   2016-01-01
1   2016-01-01
2   2016-01-01
3   2016-01-01
4   2016-01-01
Name: FL_DATE, dtype: datetime64[us]
0   2017-01-01
1   2017-01-01
2   2017-01-01
3   2017-01-01
4   2017-01-01
Name: FL_DATE, dtype: datetime64[us]
0   2018-01-01
1   2018-01-01
2   2018-01-01
3   2018-01-01
4   2018-01-01
Name: FL_DATE, dtype: datetime64[us]

##### Weather changing

In [20]:
airport_weather['date'] = pd.to_datetime(airport_weather['date'])

def wmo_condition(code):
    if code == 0:
        return "Clear"
    elif code in [1,2,3]:
        return "Cloudy"
    elif 51 <= code <= 57:
        return "Drizzle"
    elif 61 <= code <= 67:
        return "Rain"
    elif 71 <= code <= 75:
        return "Snow"
    elif 80 <= code <= 82:
        return "Showers"
    elif 95 <= code <= 99:
        return "Thunderstorm"
    else:
        return "Other"

In [21]:
airport_weather.head()
airport_weather.describe()

,date,temp_max_c,temp_min_c,precipitation_mm,wind_speed_mph,snow_mm,weather_code
count,6576,6576.000000,6576.000000,6576.000000,6576.000000,6576.000000,6576.000000
mean,2017-07-01 12:00:00,19.980338,12.612059,3.029456,19.279471,0.073704,30.833029
min,2016-01-01 00:00:00,-21.300000,-34.300000,0.000000,4.000000,0.000000,0.000000
25%,2016-09-30 18:00:00,13.600000,4.400000,0.000000,14.500000,0.000000,3.000000
50%,2017-07-01 12:00:00,25.150000,17.900000,0.000000,18.400000,0.000000,51.000000
75%,2018-04-01 06:00:00,29.000000,24.500000,1.900000,23.200000,0.000000,55.000000
max,2018-12-31 00:00:00,43.500000,31.600000,175.300000,92.100000,8.050000,75.000000
std,NaN,12.761129,14.791507,8.702954,6.833594,0.401309,28.753651

### Making a Docker to Connect to SQL in Data Grip

In [22]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar())

1

In [23]:
import pandas as pd

takeoffs2016 = pd.read_csv("data/2016.csv")
takeoffs2017 = pd.read_csv("data/2017.csv")
takeoffs2018 = pd.read_csv("data/2018.csv")

In [24]:
takeoffs2016.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2016-01-01,DL,1248,DTW,LAX,1935,1935.0,0.0,23.0,1958.0,...,309.0,285.0,249.0,1979.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,DL,1251,ATL,GRR,2125,2130.0,5.0,13.0,2143.0,...,116.0,109.0,92.0,640.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,DL,1254,LAX,ATL,2255,2256.0,1.0,19.0,2315.0,...,245.0,231.0,207.0,1947.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,DL,1255,SLC,ATL,1656,1700.0,4.0,12.0,1712.0,...,213.0,193.0,173.0,1590.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,DL,1256,BZN,MSP,900,1012.0,72.0,63.0,1115.0,...,136.0,188.0,121.0,874.0,72.0,0.0,52.0,0.0,0.0,NaN

In [25]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar())

1

In [26]:
file_path = "data/2016.csv"
table_name = "takeoffs_2016"

first_chunk = True

for chunk in pd.read_csv(file_path, chunksize=50_000):
    chunk.columns = chunk.columns.str.lower()

    chunk.to_sql(
        table_name,
        engine,
        if_exists="replace" if first_chunk else "append",
        index=False
    )

    first_chunk = False
    print(f"Wrote {len(chunk)} rows")

print("2016 table written to PostgreSQL")

Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 17658 rows
2016 table written to PostgreSQL

In [27]:
file_path = "data/2017.csv"
table_name = "takeoffs_2017"

first_chunk = True

for chunk in pd.read_csv(file_path, chunksize=50_000):
    chunk.columns = chunk.columns.str.lower()

    chunk.to_sql(
        table_name,
        engine,
        if_exists="replace" if first_chunk else "append",
        index=False
    )

    first_chunk = False
    print(f"Wrote {len(chunk)} rows")

print("2017 table written to PostgreSQL")

Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 24621 rows
2017 table written to PostgreSQL

In [28]:
file_path = "data/2018.csv"
table_name = "takeoffs_2018"

first_chunk = True

for chunk in pd.read_csv(file_path, chunksize=50_000):
    chunk.columns = chunk.columns.str.lower()

    chunk.to_sql(
        table_name,
        engine,
        if_exists="replace" if first_chunk else "append",
        index=False
    )

    first_chunk = False
    print(f"Wrote {len(chunk)} rows")

print("2018 table written to PostgreSQL")

Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 50000 rows
Wrote 13446 rows
2018 table written to PostgreSQL

In [31]:
airport_weather.to_sql(
    "airport_weather",
    engine,
    if_exists="replace",
    index=False
)

print("airport_weather table written to PostgreSQL")

airport_weather table written to PostgreSQL